version: '3'
services:
  # mssql docker
  ednevnik-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AM@R!rAm@r!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - ednevniknet2024

  ednevnik-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ednevnik-sql,1433;Database=eDnevnikIB200087;User=sa;Password=AM@R!rAm@r!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7260:7260
    networks:
      - ednevniknet2024
    links:
      - ednevnik-sql
    depends_on:
      - ednevnik-sql
      
networks:
  ednevniknet2024:
    driver: bridge
