// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eDnevnik.Services;

#nullable disable

namespace eDnevnik.Services.Migrations
{
    [DbContext(typeof(eDnevnikDBContext))]
    [Migration("20240612132955_Roles")]
    partial class Roles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eDnevnik.Services.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("KorisnikUlogaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikUlogaID"), 1L, 1);

                    b.Property<DateTime>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("UlogaID")
                        .HasColumnType("int");

                    b.HasKey("KorisnikUlogaID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("UlogaID");

                    b.ToTable("korisniciUloges");

                    b.HasData(
                        new
                        {
                            KorisnikUlogaID = 1,
                            DatumIzmjene = new DateTime(2024, 6, 12, 15, 29, 55, 192, DateTimeKind.Local).AddTicks(2152),
                            KorisnikID = 1,
                            UlogaID = 1
                        },
                        new
                        {
                            KorisnikUlogaID = 2,
                            DatumIzmjene = new DateTime(2024, 6, 12, 15, 29, 55, 192, DateTimeKind.Local).AddTicks(2237),
                            KorisnikID = 2,
                            UlogaID = 2
                        },
                        new
                        {
                            KorisnikUlogaID = 3,
                            DatumIzmjene = new DateTime(2024, 6, 12, 15, 29, 55, 192, DateTimeKind.Local).AddTicks(2240),
                            KorisnikID = 3,
                            UlogaID = 3
                        });
                });

            modelBuilder.Entity("eDnevnik.Services.Database.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikID = 1,
                            Email = "adminadmin@gmail.com",
                            Ime = "admin",
                            KorisnickoIme = "admin",
                            LozinkaHash = "",
                            LozinkaSalt = "",
                            Prezime = "admin",
                            Telefon = "+38700000000"
                        },
                        new
                        {
                            KorisnikID = 2,
                            Email = "ucenik@gmail.com",
                            Ime = "ucenik",
                            KorisnickoIme = "ucenik",
                            LozinkaHash = "",
                            LozinkaSalt = "",
                            Prezime = "ucenik",
                            Telefon = "+38700000000"
                        },
                        new
                        {
                            KorisnikID = 3,
                            Email = "roditelj@gmail.com",
                            Ime = "roditelj",
                            KorisnickoIme = "roditelj",
                            LozinkaHash = "",
                            LozinkaSalt = "",
                            Prezime = "roditelj",
                            Telefon = "+38700000000"
                        });
                });

            modelBuilder.Entity("eDnevnik.Services.Database.Proizvodi", b =>
                {
                    b.Property<int>("ProizvodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProizvodId"), 1L, 1);

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProizvodId");

                    b.ToTable("Proizvodi");

                    b.HasData(
                        new
                        {
                            ProizvodId = 1,
                            Cijena = 20m,
                            Naziv = "amar"
                        },
                        new
                        {
                            ProizvodId = 2,
                            Cijena = 30m,
                            Naziv = "alic"
                        });
                });

            modelBuilder.Entity("eDnevnik.Services.Database.Uloge", b =>
                {
                    b.Property<int>("UlogaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UlogaID");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            UlogaID = 1,
                            Naziv = "admin",
                            Opis = "admin ili profesor"
                        },
                        new
                        {
                            UlogaID = 2,
                            Naziv = "učenik",
                            Opis = "učenik/ca"
                        },
                        new
                        {
                            UlogaID = 3,
                            Naziv = "roditelj",
                            Opis = "roditelj"
                        });
                });

            modelBuilder.Entity("eDnevnik.Services.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eDnevnik.Services.Database.Korisnik", "Korisnik")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eDnevnik.Services.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("UlogaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eDnevnik.Services.Database.Korisnik", b =>
                {
                    b.Navigation("KorisniciUloge");
                });

            modelBuilder.Entity("eDnevnik.Services.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloge");
                });
#pragma warning restore 612, 618
        }
    }
}
